### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by anzi121** [firebearstudio/importexportfree#43]
Hi Team
I have installed the Extention it is not working getting an error
My Magento Version: 2.3.4

Fatal error: Uncaught Error: Call to a member function getSchema() on null in /home/adaecas1/dev.hollandandbarrett.es/vendor/firebear/importexportfree/Model/AbstractReader.php:47 Stack trace: #0 /home/adaecas1/dev.hollandandbarrett.es/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Firebear\ImportExport\Model\AbstractReader->__construct(Object(Magento\Framework\App\Config\FileResolver), Object(Magento\Framework\App\Arguments\ValidationState), Array, 'Magento\\Framewo...', 'global', '', NULL, NULL) #1 /home/adaecas1/dev.hollandandbarrett.es/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Firebear\\Import...', Array) #2 /home/adaecas1/dev.hollandandbarrett.es/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Firebear\\Import...') #3 /home/adaecas1/dev.hollandandbarrett.es/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Mag in /home/adaecas1/dev.hollandandbarrett.es/vendor/firebear/importexportfree/Model/AbstractReader.php on line 47

**Comment by henk-hypershop** [comment]
Hi @ansarul121,

I had the same issue. This error occurred due to a composer replace. We have had some import-export extension replaced. After removing them from the replace, the error was fixed.
